//////////////////////////////////////////////////////////////////////////
// Cria��o...........: 10-01-2001
// Ultima modifica��o: 20-07-2007
// Sistema...........: Olimpo Cafe - Automa��o de Cafeterias
// Analistas.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Desenvolvedores...: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Copyright.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
//////////////////////////////////////////////////////////////////////////

program Olimpo;

uses
  Forms,
  unitDmDados in 'UnitDmdados.pas' {dmDados: TDataModule},
  unitLibCredito in 'unitLibCredito.pas' {FrmLibCred},
  unitLocCliente in 'unitLocCliente.pas' {FrmLocCliente},
  UnitAtSalario in 'UnitAtSalario.pas' {FrmAtualSalario},
  UnitPrincipal in 'unitPrincipal.pas' {FrmPrincipal},
  UnitSobre in 'UnitSobre.pas' {FrmSobre},
  unitFunc in 'unitFunc.pas' {FrmFuncionario},
  UnitCargos in 'UnitCargos.pas' {FrmCargos},
  UnitProduto in 'UnitProduto.pas' {frmProduto},
  UnitComanda in 'UnitComanda.pas' {FrmComanda},
  unitOrcamento in 'unitOrcamento.pas' {FrmOrcamento},
  unitParametro in 'unitParametro.pas' {FrmParametro},
  UnitRelCliente in 'UnitRelCliente.pas' {FrmRelCliente},
  UnitQRCliente in 'UnitQRCliente.pas' {QRCliente: TQuickRep},
  unitQrPedidos in 'unitQrPedidos.pas' {QrPedidosCli},
  unitRelPedidos in 'unitRelPedidos.pas' {frmRelPedidos},
  UnitCustoFunc in 'UnitCustoFunc.pas' {FrmCustoFunc},
  unitQRVendas in 'unitQRVendas.pas' {QrVenda},
  unitQrVendasCli in 'unitQrVendasCli.pas' {QrVendaCli},
  unitQrProduto in 'unitQrProduto.pas' {QrProduto},
  unitQrPedidosFunc in 'unitQrPedidosFunc.pas' {QrPedidosFunc},
  unitQrComissao in 'unitQrComissao.pas' {QrComissao},
  UnitLocProdOut in 'UnitLocProdOut.pas' {FrmLocProdOut},
  UnitQRFunc in 'UnitQRFunc.pas' {QRFunc: TQuickRep},
  UnitRelFunc in 'UnitRelFunc.pas' {FrmRelFunc},
  UnitCadGrupo in 'unitCadGrupo.pas' {FrmCadGrupo},
  UnitCadSubgrupo in 'unitCadSubgrupo.pas' {FrmCadSubgrupo},
  UnitCadMarca in 'unitCadMarca.pas' {FrmCadMarca},
  UnitCadUnidade in 'unitCadUnidade.pas' {FrmCadUnidades},
  UnitCadSenha in 'UnitCadSenha.pas' {frmCadSenha},
  unitQrOrcamento in 'unitQrOrcamento.pas' {QrOrcamento},
  UnitLocFunc in 'UnitLocFunc.pas' {FrmLocFunc},
  UnitCadCliente in 'UnitCadCliente.pas' {FrmCadCliente},
  UnitCadPlanos in 'UnitCadPlanos.pas' {FrmCadPlanos},
  UnitConsPlano in 'UnitConsPlano.pas' {FrmConsPlano},
  untDepende in 'untDepende.pas' {frmDependentes},
  unitCadMaterial in 'unitCadMaterial.pas' {frmCadMaterial},
  unitPagaVenda in 'unitPagaVenda.pas' {frmPagaVenda},
  UnitCarne in 'UnitCarne.pas' {QRCarne: TQuickRep},
  unitPreco in 'unitPreco.pas' {FrmLocPreco},
  unitCancelVenda in 'unitCancelVenda.pas' {frmCancelVenda},
  UnitLocVenda in 'UnitLocVenda.pas' {FrmLocVenda},
  unitQrFatura in 'unitQrFatura.pas' {qrFatura},
  unitRelFatura in 'unitRelFatura.pas' {frmRelFatura},
  untOrca in 'untOrca.pas' {frmOrca},
  UnitVendas in 'UnitVendas.pas' {FrmVendas},
  UnitCidade in 'UnitCidade.pas' {FrmCidade},
  UnitFechCaixa in 'UnitFechCaixa.pas' {FrmFechCaixa},
  untFechaCx in 'untFechaCx.pas' {FrmFechaCx},
  UnitLanCaixa in 'UnitLanCaixa.pas' {FrmLanCaixa},
  UnitLocCaixa in 'UnitLocCaixa.pas' {FrmLocCaixa},
  UnitOutros in 'UnitOutros.pas' {FrmOutros},
  untBloCli in 'untBloCli.pas' {frmBloCli},
  UnitLocProd in 'UnitLocProd.pas' {FrmLocProd},
  SkinGraphic in '..\SkinGraphic.pas',
  UnitHistorico in 'UnitHistorico.pas' {FrmHistorico},
  UnitTipoDoc in 'UnitTipoDoc.pas' {FrmTipoDoc},
  UnitCadBanco in 'UnitCadBanco.pas' {FrmCadBanco},
  UnitCCorrente in 'UnitCCorrente.pas' {FrmCCorrente},
  UnitLocCP in 'UnitLocCP.pas' {FrmLocCPagar},
  UnitLocFornec in 'UnitLocFornec.pas' {FrmLocFornec},
  UnitLocCR in 'UnitLocCR.pas' {FrmLocCReceber},
  untComAberta in 'untComAberta.pas' {frmComAberta},
  untCancelar in 'untCancelar.pas' {FrmCancelar},
  untCompos in 'untCompos.pas' {FrmCompos},
  UnitRecebCli in 'UnitRecebCli.pas' {FrmRecebCli},
  UnitEntMat in 'UnitEntMat.pas' {FrmEntrMat},
  UnitSaidaMat in 'unitSaidaMat.pas' {FrmSaidaMat},
  Unitcompra1 in 'Unitcompra1.pas' {FrmRelCompras},
  unitRelCompras in 'unitRelCompras.pas' {FrmRelCompPer},
  UnitRelEstoque in 'UnitRelEstoque.pas' {FrmRelEstoque},
  untQrTabelaPreco in 'untQrTabelaPreco.pas' {QrTabelaPreco: TQuickRep},
  untQrInvent2 in 'untQrInvent2.pas' {QrInvent2: TQuickRep},
  untQrInventario in 'untQrInventario.pas' {QrInventario: TQuickRep},
  Unitqrcompra1 in 'Unitqrcompra1.pas' {qrcompra1: TQuickRep},
  unitQrCompra in 'unitQrCompra.pas' {QrCompra},
  UnitQREstoque in 'UnitQREstoque.pas' {QREstoque: TQuickRep},
  untMovDia in 'untMovDia.pas' {QrMovDia: TQuickRep},
  untRelVendas in 'untRelVendas.pas' {frmRelVendas},
  untRelFechaCaixa in 'untRelFechaCaixa.pas' {qrFechaCaixa: TQuickRep},
  UnitBaixaLoteCR in 'UnitBaixaLoteCR.pas' {FrmBaixaLoteCR},
  UnitBaixaLoteCP in 'UnitBaixaLoteCP.pas' {FrmBaixaLoteCP},
  UnitCancelCP in 'UnitCancelCP.pas' {FrmCancelCP},
  UnitCancelCR in 'UnitCancelCR.pas' {FrmCancelCR},
  unitCpagar in 'UnitCPagar.pas' {FrmCPagar},
  unitCreceber in 'UnitCReceber.pas' {FrmCReceber},
  UnitFechCC in 'UnitFechCC.pas' {FrmFechCC},
  UnitMovCaixa in 'UnitMovCaixa.pas' {FrmMovCaixa},
  UnitTipoPagto in 'UnitTipoPagto.pas' {FrmTipoPgto},
  untRecebComa in 'untRecebComa.pas' {frmRecebComa},
  unitLocTipoDoc in 'UnitLocTipoDoc.pas' {FrmLocTipoDoc},
  UnitTransf in 'UnitTransf.pas' {FrmTransf},
  UnitChequeEmit in 'UnitChequeEmit.pas' {FrmChequeEmit},
  UnitExtrato in 'UnitExtrato.pas' {FrmExtrato},
  UnitSaldo in 'UnitSaldo.pas' {FrmSaldo},
  UnitSaldoCons in 'UnitSaldoCons.pas' {FrmSaldoCons},
  UnitFechBanc in 'UnitFechBanc.pas' {FrmFechBanc},
  unitSelecCR in 'unitSelecCR.pas' {FrmSelecCR},
  UnitSelecCP in 'UnitSelecCP.pas' {FrmSelecCP},
  UnitDescParc in 'UnitDescParc.pas' {FrmDescParc},
  UnitTipoReceb in 'UnitTipoReceb.pas' {FrmTipoReceb},
  unitLanCheque in 'UnitLanCheque.pas' {FrmLanCheque},
  unitBaixaCheque in 'unitBaixaCheque.pas' {FrmBaixaCheque},
  unitLanChequeSF in 'unitLanChequeSF.pas' {frmLanChequeSF},
  unitRenCheque in 'unitRenCheque.pas' {FrmRengCheque},
  unitConsultaCPF in 'unitConsultaCPF.pas' {FrmConsultaCPF},
  unitRelCheAberto in 'unitRelCheAberto.pas' {frmRelCheAberto},
  untRelCheDev in 'untRelCheDev.pas' {frmRelCheDev},
  untRelCheDevCli in 'untRelCheDevCli.pas' {frmRelCheDevCli},
  UnitCadFornec in 'UnitCadFornec.pas' {FrmCadFornec},
  untFechaCli in 'untFechaCli.pas' {frmFechaCli},
  UnitTroco in 'UnitTroco.pas' {FrmTroco},
  UnitCredConta in 'UnitCredConta.pas' {FrmCredConta},
  UnitAbreCx in 'UnitAbreCx.pas' {FrmAbreCx},
  UnitRelCReceber in 'UnitRelCReceber.pas' {FrmRelCReceber},
  UnitQRCReceber in 'UnitQRCReceber.pas' {QRCreceber: TQuickRep},
  untMotivo in 'untMotivo.pas' {FrmMotivo},
  UnitQRFornec in 'UnitQRFornec.pas' {QRFornec: TQuickRep},
  UnitRelFornec in 'UnitRelFornec.pas' {FrmRelFornec},
  unitQRBalFin in 'unitQRBalFin.pas' {qrBalFin: TQuickRep},
  unitRelCpagar in 'unitRelCpagar.pas' {FrmRelCpagar},
  unitBalFin in 'unitBalFin.pas' {FrmBalFin},
  uitQrSaExtratos in 'uitQrSaExtratos.pas' {QrSaExtrato},
  unitQrImposto in 'unitQrImposto.pas' {QrImposto},
  untFatProd in 'untFatProd.pas' {qrFatPro: TQuickRep},
  untRelCaixa in 'untRelCaixa.pas' {qrCaixa: TQuickRep},
  untCCliente in 'untCCliente.pas' {FrmCCliente},
  UnitDetConta in 'UnitDetConta.pas' {FrmDetConta};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Olimpo Vers�o 2.1';
  Application.CreateForm(TdmDados, dmDados);
  Application.CreateForm(TFrmPrincipal, FrmPrincipal);
  Application.CreateForm(TFrmDetConta, FrmDetConta);
  Application.Run;
end.
